title: Longer95479-Blog
description: "Longer95479's Blog"
author:
  name: "Longer95479"
  email: "Longer95479@gmail.com"
  url: "https://Longer95479.github.io"

baseurl: ""

source: .
destination: ./_site
permalink: /:title/
paginate: 10
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "Longer95479"
year : "2024"
